Try using action YAML in Linux workflow

diff --git a/.github/workflows/xlingpaper-linux-build-config-release.yml b/.github/workflows/xlingpaper-linux-build-config-release.yml
--- a/.github/workflows/xlingpaper-linux-build-config-release.yml
+++ b/.github/workflows/xlingpaper-linux-build-config-release.yml
@@ -18,26 +18,25 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: '0'
-
-      - name: Set VERSION (e.g. 1.0.0) and FULL_VERSION (e.g. 1.0.0-abcdef4)
-        run: |
-          VERSION="${GITHUB_REF#refs/tags/v}"
-          SHORT_SHA=$(git rev-parse --short HEAD)
-          FULL_VERSION="${VERSION}-${SHORT_SHA}"
-          LINUXTARGET="24.04"
-          echo "VERSION=${VERSION}" >> $GITHUB_ENV
-          echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_ENV
-          echo "LINUXTARGET=${LINUXTARGET}" >> $GITHUB_ENV
-        shell: bash
-
-      - name: Validate version format
-        run: |
-          echo ${VERSION}
-          if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Error: Version format is incorrect. It should match N.N.N where N is an integer."
-            exit 1
-          fi
-        shell: bash
+      - name: Set and validate version
+        uses: ./.github/actions/set-validate-version
+#      - name: Set VERSION (e.g. 1.0.0) and FULL_VERSION (e.g. 1.0.0-abcdef4)
+#        run: |
+#          VERSION="${GITHUB_REF#refs/tags/v}"
+#          SHORT_SHA=$(git rev-parse --short HEAD)
+#          FULL_VERSION="${VERSION}-${SHORT_SHA}"
+#          echo "VERSION=${VERSION}" >> $GITHUB_ENV
+#          echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_ENV
+#        shell: bash
+#
+#      - name: Validate version format
+#        run: |
+#          echo ${VERSION}
+#          if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+#            echo "Error: Version format is incorrect. It should match N.N.N where N is an integer."
+#            exit 1
+#          fi
+#        shell: bash
 
       - name: 'Prepare for Java compilation'
         run: |
