macOS sign config: try 1

diff --git a/.github/workflows/xlingpaper-macos-build-config-sign-release.yml b/.github/workflows/xlingpaper-macos-build-config-sign-release.yml
--- a/.github/workflows/xlingpaper-macos-build-config-sign-release.yml
+++ b/.github/workflows/xlingpaper-macos-build-config-sign-release.yml
@@ -1,17 +1,19 @@
 # This workflow will build an installer for XLingPaper config-only
 
-name: XLingPaper macOS Config Build Installer with Version
+name: XLingPaper macOS Config Build Signed Installer with Version
+
+env:
+  NOTARIZE_PASSWORD: ${{ secrets.SIL_APPLE_NOTARIZATION_PASSWORD }}
+  NOTARIZE_APPLE_ID: ${{ secrets.SIL_APPLE_NOTARIZATION_USERNAME }}
+  NOTARIZE_TEAM_ID: ${{ secrets.SIL_APPLE_NOTARIZATION_USERNAME }}
 
 on:
   push:
-    paths:
-      - ".github/workflows/xlingpaper-macos-build-config-sign-releaseHOLD.yml"
+    tags:
+      - 'v*'  # Build the app for commits that are tagged starting with 'v' e.g. v1.2.3
+      # to tag a commit, use "git tag v1.2.3"
+      # when you then use "git push origin v1.2.3" this workflow will be invoked
 #    branches: [ "GHAInstallers" ]
-#    tags:
-#      - 'v*'  # Build the app for commits that are tagged starting with 'v' e.g. v1.2.3
-#      # to tag a commit, use "git tag v1.2.3"
-#      # when you then use "git push origin v1.2.3" this workflow will be invoked
-#  workflow_dispatch:
 
 jobs:
   build-installer:
@@ -24,24 +26,21 @@ jobs:
 
       - name: Set VERSION (e.g. 1.0.0) and FULL_VERSION (e.g. 1.0.0-abcdef4)
         run: |
-          VERSION="3.18.3"
-#          VERSION="${GITHUB_REF#refs/tags/v}"
-#          SHORT_SHA=$(git rev-parse --short HEAD)
-#          FULL_VERSION="${VERSION}-${SHORT_SHA}"
-#          LINUXTARGET="24.04"
-#          echo "VERSION=${VERSION}" >> $GITHUB_ENV
-#          echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_ENV
-#          echo "LINUXTARGET=${LINUXTARGET}" >> $GITHUB_ENV
+          VERSION="${GITHUB_REF#refs/tags/v}"
+          SHORT_SHA=$(git rev-parse --short HEAD)
+          FULL_VERSION="${VERSION}-${SHORT_SHA}"
+          echo "VERSION=${VERSION}" >> $GITHUB_ENV
+          echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_ENV
         shell: bash
 
-#      - name: Validate version format
-#        run: |
-#          echo ${VERSION}
-#          if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-#            echo "Error: Version format is incorrect. It should match N.N.N where N is an integer."
-#            exit 1
-#          fi
-#        shell: bash
+      - name: Validate version format
+        run: |
+          echo ${VERSION}
+          if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Version format is incorrect. It should match N.N.N where N is an integer."
+            exit 1
+          fi
+        shell: bash
 
 #      - name: 'Prepare for Java compilation'
 #        run: |
@@ -133,9 +132,10 @@ jobs:
           ls -l
           ls -l build
           cd build
-          productsign --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" \
-             XLingPaperConfigurationFiles7n8-3.18.3.pkg \
-             XLingPaperConfigurationFiles7n8-3.18.3Signed.pkg
+          codesign --force --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" --timestamp --options runtime XLingPaperConfigurationFiles7n8-3.18.3.pkg -v
+#          productsign --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" \
+#             XLingPaperConfigurationFiles7n8-3.18.3.pkg \
+#             XLingPaperConfigurationFiles7n8-3.18.3Signed.pkg
 #          productsign --sign "${{ vars.SIL_APPLE_CODESIGN_IDENTITY }}" \
 #             XLingPaperConfigurationFiles7n8-${{ env.VERSION }}.pkg \
 #             XLingPaperConfigurationFiles7n8-${{ env.VERSION }}Signed.pkg
