macos sign config only installer, try 2

diff --git a/.github/workflows/xlingpaper-macos-build-config-sign-release.yml b/.github/workflows/xlingpaper-macos-build-config-sign-release.yml
--- a/.github/workflows/xlingpaper-macos-build-config-sign-release.yml
+++ b/.github/workflows/xlingpaper-macos-build-config-sign-release.yml
@@ -22,23 +22,24 @@ jobs:
 
       - name: Set VERSION (e.g. 1.0.0) and FULL_VERSION (e.g. 1.0.0-abcdef4)
         run: |
-          VERSION="${GITHUB_REF#refs/tags/v}"
-          SHORT_SHA=$(git rev-parse --short HEAD)
-          FULL_VERSION="${VERSION}-${SHORT_SHA}"
-          LINUXTARGET="24.04"
-          echo "VERSION=${VERSION}" >> $GITHUB_ENV
-          echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_ENV
-          echo "LINUXTARGET=${LINUXTARGET}" >> $GITHUB_ENV
+          VERSION="3.18.3"
+#          VERSION="${GITHUB_REF#refs/tags/v}"
+#          SHORT_SHA=$(git rev-parse --short HEAD)
+#          FULL_VERSION="${VERSION}-${SHORT_SHA}"
+#          LINUXTARGET="24.04"
+#          echo "VERSION=${VERSION}" >> $GITHUB_ENV
+#          echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_ENV
+#          echo "LINUXTARGET=${LINUXTARGET}" >> $GITHUB_ENV
         shell: bash
 
-      - name: Validate version format
-        run: |
-          echo ${VERSION}
-          if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Error: Version format is incorrect. It should match N.N.N where N is an integer."
-            exit 1
-          fi
-        shell: bash
+#      - name: Validate version format
+#        run: |
+#          echo ${VERSION}
+#          if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+#            echo "Error: Version format is incorrect. It should match N.N.N where N is an integer."
+#            exit 1
+#          fi
+#        shell: bash
 
 #      - name: 'Prepare for Java compilation'
 #        run: |
